@echo off
cd C:\Users\%USERNAME%\Downloads
(
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
echo bowling bee 🎳🐝
) > bowlingbee.txt
start notepad.exe bowlingbee.txt
